### ISSUE TITLE
network and input size

### ISSUE THREAD

**Issue by ROBOTICSENGINEER** [yenchanghsu/Generalized-ODIN#3]
Did you used standard resnet and densenet with standard input size (224 x 224)? or did you use modified version of this networks with different input size?

**Comment by yenchanghsu** [comment]
The resnet and densenet for CIFAR are the same as [here] (https://github.com/pokaxpoka/deep_Mahalanobis_detector/tree/master/models) which has input size 32x32.

The model for the DomainNet dataset is the standard resnet with a standard input size 224x224.
