### ISSUE TITLE
out of distribution images datasets

### ISSUE THREAD

**Issue by ROBOTICSENGINEER** [yenchanghsu/Generalized-ODIN#4]
what is transformation of out of distribution, resize to what, and how does it crop?

Can you share the link to where you download the out of distribution images datasets?

**Comment by yenchanghsu** [comment]
The OOD images can be downloaded [here](https://drive.google.com/open?id=1E89O3VZ30XKoZ-bIP12k3I2shMyE3mp4). 

Below is how OOD images are processed with PyTorch:
```python
transform = transforms.Compose([
        transforms.CenterCrop((32, 32)),
        transforms.ToTensor(),
        transforms.Normalize(mean=mean, std=std),
    ])
# mean and std is the same as your training data preprocessing
```
